-- ========================================================
-- ULTIMATE DATABASE SETUP (SUPABASE)
-- ========================================================

-- 0. EXTENSIONS & SETUP
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. ADMINS / STAFF (Authentication)
CREATE TABLE IF NOT EXISTS public.admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT,
    shop_name TEXT,
    shop_id TEXT DEFAULT 'SHOP-MLAM4TC6-JHD',
    role TEXT DEFAULT 'staff', -- admin, staff, superadmin
    admin_id BIGINT REFERENCES public.admins(id), -- หัวหน้า (สำหรับพนักงาน)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP-MLAM4TC6-JHD',
    name TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(shop_id, name)
);

-- 3. CUSTOMERS
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP-MLAM4TC6-JHD',
    name TEXT NOT NULL,
    phone TEXT NOT NULL UNIQUE,
    points INTEGER DEFAULT 0,
    total_spent DECIMAL(10,2) DEFAULT 0,
    birthday DATE,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP001',
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    cost DECIMAL(10,2) DEFAULT 0,
    category_id BIGINT REFERENCES public.categories(id),
    image_url TEXT,
    stock INTEGER DEFAULT 0,
    barcode TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_by BIGINT REFERENCES public.admins(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_images (
    id BIGSERIAL PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    is_main BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. STOCK TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.stock_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id),
    qty INTEGER NOT NULL,
    type TEXT NOT NULL, -- IN, OUT, ADJUST
    reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. SALES & TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_number TEXT,
    customer_id BIGINT REFERENCES public.customers(id),
    staff_id BIGINT REFERENCES public.admins(id),
    subtotal DECIMAL(10,2),
    discount DECIMAL(10,2) DEFAULT 0,
    total DECIMAL(10,2) NOT NULL,
    amount_received DECIMAL(10,2),
    change_amount DECIMAL(10,2),
    payment_method TEXT NOT NULL DEFAULT 'cash',
    coupon_code TEXT,
    points_redeemed INTEGER DEFAULT 0,
    status TEXT DEFAULT 'completed', -- completed, void
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT REFERENCES public.sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    product_name TEXT,
    quantity INTEGER NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. HELD BILLS (พักบิล)
CREATE TABLE IF NOT EXISTS public.held_bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id),
    subtotal DECIMAL(10,2),
    discount DECIMAL(10,2) DEFAULT 0,
    total DECIMAL(10,2) NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.held_bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    held_bill_id BIGINT REFERENCES public.held_bills(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id),
    product_name TEXT,
    price DECIMAL(10,2) NOT NULL,
    quantity INTEGER NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL
);

-- 8. PROMOTIONS & COUPONS
CREATE TABLE IF NOT EXISTS public.promotions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP001',
    name TEXT NOT NULL,
    description TEXT,
    discount_type TEXT NOT NULL, -- percentage, fixed_amount
    discount_value DECIMAL(10,2) NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.promotion_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id BIGINT REFERENCES public.promotions(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(promotion_id, product_id)
);

CREATE TABLE IF NOT EXISTS public.coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP001',
    code TEXT NOT NULL UNIQUE,
    description TEXT,
    discount_type TEXT NOT NULL,
    discount_value DECIMAL(10,2) NOT NULL,
    min_spend DECIMAL(10,2) DEFAULT 0,
    max_usage INTEGER,
    current_usage INTEGER DEFAULT 0,
    expiry_date TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. NEWS & MARKETING
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP001',
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    image_url TEXT,
    is_published BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 10. REWARDS & REDEMPTIONS
CREATE TABLE IF NOT EXISTS public.rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP-MLAM4TC6-JHD',
    name TEXT NOT NULL,
    description TEXT,
    points_required INTEGER NOT NULL,
    image_url TEXT,
    stock INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.reward_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id),
    reward_id BIGINT REFERENCES public.rewards(id),
    points_spent INTEGER NOT NULL,
    redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    status TEXT DEFAULT 'completed'
);

-- 11. STORE SETTINGS
CREATE TABLE IF NOT EXISTS public.store_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP-MLAM4TC6-JHD',
    name TEXT NOT NULL DEFAULT 'Smart POS',
    address TEXT,
    phone TEXT,
    tax_id TEXT,
    logo_url TEXT,
    promptpay_number TEXT,
    promptpay_name TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 12. STAFF LOGS
CREATE TABLE IF NOT EXISTS public.staff_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id TEXT DEFAULT 'SHOP-MLAM4TC6-JHD',
    staff_id BIGINT REFERENCES public.admins(id),
    action TEXT NOT NULL,
    details JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 13. ACTIVE CARTS (Shared Cart System)
CREATE TABLE IF NOT EXISTS public.active_carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id TEXT, -- Can be null or link to admin/staff
    customer_id BIGINT REFERENCES public.customers(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.active_cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT REFERENCES public.active_carts(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    quantity INTEGER DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ========================================================
-- SEED DATA (MASSIVE DEMO DATA)
-- ========================================================

-- 1. ADMIN / SHOP SETUP
-- Password is '123456789' hashed with bcrypt
INSERT INTO public.admins (username, password_hash, name, shop_name, shop_id, role)
VALUES (
    'smartpos', 
    '$2b$10$IP/.v4RkWPjCufhMEosA9unDC77bJsFAnySWVRx/TKixCINkxRMxK', 
    'Administrator', 
    'SmartPOS', 
    'SHOP-MLAM4TC6-JHD', 
    'admin'
) ON CONFLICT (username) DO NOTHING;

-- 2. DYNAMIC MOCK DATA GENERATION (PL/pgSQL)
DO $$
DECLARE
    i INTEGER;
    cat_id BIGINT;
    cat_names TEXT[] := ARRAY['กาแฟยอดฮิต', 'ชาพรีเมียม', 'เครื่องดื่มเย็น', 'เบเกอรี่อบใหม่', 'เค้กและของหวาน', 'อาหารเช้า', 'ของทานเล่น', 'เมล็ดกาแฟ', 'ชาเขียวมัทฉะ', 'น้ำผลไม้สกัด', 'สมูทตี้', 'โซดาผลไม้', 'นมหอมหวาน', 'แซนวิช', 'สลัดสุขภาพ', 'เซ็ตมื้อกลางวัน', 'พาสต้า', 'สเต็กยอดนิยม', 'ผลไม้สด', 'เครื่องเคียง', 'เมนูพิเศษ', 'สินค้าที่ระลึก', 'อุปกรณ์ชงกาแฟ', 'แก้วสะสม', 'ถุงพ่วง', 'เซ็ตของขวัญ', 'เมนูเจ', 'เมนูมังสวิรัติ', 'อาหารคลีน', 'ขนมปังฝรั่งเศส', 'คุกกี้โฮมเมด', 'ช็อกโกแลตเข้มข้น', 'ไอศกรีมมหาชัย', 'เครื่องดื่มอุ่น', 'เมนูฤดูร้อน', 'เมนูคริสต์มาส', 'เทศกาลไหว้พระจันทร์', 'กู้ดส์ดีไซน์', 'แพ็กเกจจิ้ง', 'เมนูแนะนำประจำสัปดาห์'];
BEGIN
    -- 2.1 CATEGORIES (40 items)
    FOR i IN 1..40 LOOP
        INSERT INTO public.categories (shop_id, name, description, icon)
        VALUES ('SHOP-MLAM4TC6-JHD', cat_names[i], 'กลุ่มสินค้าคุณภาพในหมวด ' || cat_names[i], 'Coffee')
        ON CONFLICT (shop_id, name) DO NOTHING;
    END LOOP;

    -- 2.2 PRODUCTS (100,000 items)
    DECLARE
        cat_rec RECORD;
        base_name TEXT;
        img_keyword TEXT;
        final_name TEXT;
        
        -- Data Arrays
        coffee_names TEXT[] := ARRAY['Espresso', 'Americano', 'Latte', 'Cappuccino', 'Mocha', 'Caramel Macchiato', 'Dirty Coffee', 'Cold Brew', 'Nitro Cold Brew', 'Piccolo'];
        tea_names TEXT[] := ARRAY['Green Tea Latte', 'Thai Tea', 'Black Tea', 'Earl Grey', 'Chamomile', 'Jasmine Tea', 'Peach Tea', 'Lemon Tea', 'Oolong Tea', 'Matcha Frappe'];
        bakery_names TEXT[] := ARRAY['Plain Croissant', 'Almond Croissant', 'Chocolate Cake', 'Blueberry Cheesecake', 'Tiramisu', 'Macaron', 'Brownie', 'Waffle', 'Toast', 'Bagel'];
        food_names TEXT[] := ARRAY['Club Sandwich', 'Caesar Salad', 'Spaghetti Carbonara', 'Beef Burger', 'French Fries', 'Chicken Wings', 'Pork Steak', 'Beef Steak', 'Salmon Steak', 'Tom Yum Kung', 'Pad Thai'];
        
        modifiers TEXT[] := ARRAY['Hot', 'Iced', 'Frappe', 'Signature', 'Premium', 'Special', 'Supreme'];
    BEGIN
        FOR i IN 1..5000 LOOP
            -- Select random category including its name
            SELECT id, name INTO cat_rec FROM public.categories ORDER BY random() LIMIT 1;
            
            -- Determine Base Name and Image Keyword based on Category Name
            IF (cat_rec.name LIKE '%กาแฟ%' OR cat_rec.name LIKE '%Coffee%' OR cat_rec.name LIKE '%เมล็ด%') THEN
                 base_name := coffee_names[1 + floor(random() * array_length(coffee_names, 1))];
                 img_keyword := 'coffee,latte';
            ELSIF (cat_rec.name LIKE '%ชา%' OR cat_rec.name LIKE '%Tea%' OR cat_rec.name LIKE '%มัทฉะ%') THEN
                 base_name := tea_names[1 + floor(random() * array_length(tea_names, 1))];
                 img_keyword := 'tea,drink';
            ELSIF (cat_rec.name LIKE '%เค้ก%' OR cat_rec.name LIKE '%เบเกอรี่%' OR cat_rec.name LIKE '%ขนม%' OR cat_rec.name LIKE '%หวาน%') THEN
                 base_name := bakery_names[1 + floor(random() * array_length(bakery_names, 1))];
                 img_keyword := 'cake,pastry';
            ELSE
                 base_name := food_names[1 + floor(random() * array_length(food_names, 1))];
                 img_keyword := 'food,restaurant';
            END IF;

            final_name := base_name || ' ' || modifiers[1 + floor(random() * array_length(modifiers, 1))];

            INSERT INTO public.products (shop_id, name, description, price, cost, category_id, stock, barcode, created_by, image_url)
            VALUES (
                'SHOP-MLAM4TC6-JHD',
                final_name || ' #' || i, -- Ensure uniqueness
                'เมนูแนะนำ: ' || base_name || ' ปรุงสดใหม่ด้วยวัตถุดิบคุณภาพดี (รหัสสินค้า: ' || i || ')',
                (45 + (random() * 200))::DECIMAL(10,2), 
                (20 + (random() * 50))::DECIMAL(10,2),
                cat_rec.id, -- Use selected category ID
                (random() * 100)::INTEGER,
                '885' || LPAD(i::text, 10, '0'),
                (SELECT id FROM public.admins LIMIT 1),
                'https://loremflickr.com/400/400/' || img_keyword || '?lock=' || i -- Consistent random image
            );
        END LOOP;
    END;

    -- 2.3 REWARDS (100 items)
    FOR i IN 1..100 LOOP
        INSERT INTO public.rewards (shop_id, name, description, points_required, stock, active)
        VALUES (
            'SHOP-MLAM4TC6-JHD',
            'ของรางวัลที่ ' || i,
            'แลกรับของรางวัลพิเศษชิ้นที่ ' || i,
            (50 + (i * 10)), -- 60, 70, 80... points
            (random() * 20)::INTEGER,
            TRUE
        );
    END LOOP;

    -- 2.4 PROMOTIONS (10 items - New Store Opening)
    FOR i IN 1..10 LOOP
        INSERT INTO public.promotions (shop_id, name, description, discount_type, discount_value, start_date, end_date, is_active)
        VALUES (
            'SHOP-MLAM4TC6-JHD',
            'ฉลองเปิดร้านใหม่ โปรโมชั่นที่ ' || i,
            'พิเศษสุดคุ้มเฉพาะช่วงเปิดตัว รับส่วนลดทันที',
            CASE WHEN i % 2 = 0 THEN 'percentage' ELSE 'fixed_amount' END,
            CASE WHEN i % 2 = 0 THEN 10 ELSE 20 END,
            NOW(),
            NOW() + INTERVAL '30 days',
            TRUE
        );
    END LOOP;

    -- 2.5 COUPONS (100 items)
    FOR i IN 1..100 LOOP
        INSERT INTO public.coupons (shop_id, code, description, discount_type, discount_value, min_spend, max_usage, expiry_date, is_active)
        VALUES (
            'SHOP-MLAM4TC6-JHD',
            'WELCOME' || LPAD(i::text, 3, '0'),
            'คูปองต้อนรับส่วนลดแจกฟรี ชุดที่ ' || i,
            'fixed_amount',
            (10 + (random() * 40))::INTEGER,
            100,
            10,
            NOW() + INTERVAL '60 days',
            TRUE
        );
    END LOOP;
    -- 2.6 SALES (2,000 items over last 2 years)
    FOR i IN 1..2000 LOOP
        DECLARE
            sale_id BIGINT;
            total_amount DECIMAL(10,2) := 0;
            item_count INTEGER := (floor(random() * 5) + 1)::INTEGER;
            current_product RECORD;
            sale_date TIMESTAMP WITH TIME ZONE := NOW() - (random() * INTERVAL '730 days');
            staff_id BIGINT := (SELECT id FROM public.admins LIMIT 1);
        BEGIN
            -- Insert Sale Header
            INSERT INTO public.sales (bill_number, staff_id, subtotal, discount, total, payment_method, created_at)
            VALUES (
                'INV-' || to_char(sale_date, 'YYYYMMDD') || '-' || LPAD(i::text, 4, '0'),
                staff_id,
                0, -- temporary
                0,
                0, -- temporary
                CASE WHEN (random() > 0.5) THEN 'QR' ELSE 'Cash' END,
                sale_date
            ) RETURNING id INTO sale_id;

            -- Insert Sale Items
            FOR j IN 1..item_count LOOP
                SELECT id, name, price INTO current_product FROM public.products ORDER BY random() LIMIT 1;
                
                INSERT INTO public.sale_items (sale_id, product_id, product_name, quantity, price, subtotal, created_at)
                VALUES (
                    sale_id,
                    current_product.id,
                    current_product.name,
                    (floor(random() * 3) + 1)::INTEGER,
                    current_product.price,
                    (current_product.price * (floor(random() * 3) + 1)),
                    sale_date
                );
                
                total_amount := total_amount + (current_product.price * (floor(random() * 3) + 1));
            END LOOP;

            -- Update Sale Totals
            UPDATE public.sales 
            SET subtotal = total_amount, total = total_amount 
            WHERE id = sale_id;
        END;
    END LOOP;
END $$;

-- 2.12 ADDITIONAL SEED DATA (Customers, News, Logs, Promo Products)
DO $$
DECLARE
    i INTEGER;
    cust_id BIGINT;
    promo_id BIGINT;
    prod_id BIGINT;
BEGIN
    -- CUSTOMERS (50 items)
    FOR i IN 1..50 LOOP
        INSERT INTO public.customers (shop_id, name, phone, points, total_spent, birthday, image_url)
        VALUES (
            'SHOP-MLAM4TC6-JHD',
            'ลูกค้าทดสอบ ' || i,
            '08' || LPAD(i::text, 8, '0'),
            (random() * 500)::INTEGER,
            (random() * 10000)::DECIMAL(10,2),
            NOW() - (random() * INTERVAL '10000 days'),
            'https://placehold.co/200x200?text=User' || i
        ) ON CONFLICT (phone) DO NOTHING;
    END LOOP;

    -- NEWS (10 items)
    FOR i IN 1..10 LOOP
        INSERT INTO public.news (shop_id, title, content, image_url, is_published)
        VALUES (
            'SHOP-MLAM4TC6-JHD',
            'ข่าวสารประชาสัมพันธ์ที่ ' || i,
            'รายละเอียดข่าวสารกิจกรรมร้านค้า... โปรโมชั่นพิเศษต้อนรับเทศกาลต่างๆ',
            'https://placehold.co/600x400?text=News' || i,
            TRUE
        );
    END LOOP;

    -- STAFF LOGS (20 items)
    FOR i IN 1..20 LOOP
        INSERT INTO public.staff_logs (shop_id, staff_id, action, details)
        VALUES (
            'SHOP-MLAM4TC6-JHD',
            (SELECT id FROM public.admins LIMIT 1),
            CASE WHEN i % 2 = 0 THEN 'LOGIN' ELSE 'CREATE_SALE' END,
            '{"ip": "127.0.0.1", "device": "chrome"}'::jsonb
        );
    END LOOP;

    -- PROMOTION PRODUCTS
    FOR promo_id IN (SELECT id FROM public.promotions) LOOP
        FOR i IN 1..3 LOOP
             prod_id := (SELECT id FROM public.products ORDER BY random() LIMIT 1);
             BEGIN
                INSERT INTO public.promotion_products (promotion_id, product_id)
                VALUES (promo_id, prod_id);
             EXCEPTION WHEN unique_violation THEN
                -- Ignore
             END;
        END LOOP;
    END LOOP;

    -- UPDATE SALES with Customers
    UPDATE public.sales
    SET customer_id = (SELECT id FROM public.customers ORDER BY random() LIMIT 1)
    WHERE random() > 0.5;

END $$;

-- 3. INITIAL SETTINGS
INSERT INTO public.store_settings (name, address, phone, shop_id)
SELECT 'SmartPOS Flagship Store', '123 ถนนเพลินจิต กรุงเทพมหานคร', '02-123-4567', 'SHOP-MLAM4TC6-JHD'
WHERE NOT EXISTS (SELECT 1 FROM public.store_settings);

-- 4. BUCKETS (STORAGE)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- 5. INDEXES
CREATE INDEX IF NOT EXISTS idx_products_shop_id ON products(shop_id);
CREATE INDEX IF NOT EXISTS idx_products_barcode ON products(barcode);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_bill_number ON sales(bill_number);
CREATE INDEX IF NOT EXISTS idx_sales_customer_id ON sales(customer_id);
CREATE INDEX IF NOT EXISTS idx_promotions_shop_id ON promotions(shop_id);

-- 6. PERMISSIONS & SECURITY (CRITICAL CORRECTION)
GRANT USAGE ON SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO postgres, anon, authenticated, service_role;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO postgres, anon, authenticated, service_role;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO postgres, anon, authenticated, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO postgres, anon, authenticated, service_role;

-- Disable RLS to prevent "infinite recursion" or "policy" blocking in this MVP phase
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'ALTER TABLE public.' || quote_ident(r.tablename) || ' DISABLE ROW LEVEL SECURITY;';
    END LOOP;
END $$;
